version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    # image: nullpon/mywp:5.1.1-php7.1-apache
    image: nullpon/mywp:5.6-php7.4
    depends_on:
      - db
    volumes:
      - html:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./_wp-content:/var/www/html/wp-content
      - ./resource:/var/www/html/wp-content/themes/resource
    links:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      VIRTUAL_HOST: ${VIRTUAL_NAME},www.${VIRTUAL_NAME}
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      VIRTUAL_HOST: phpmyadmin.${VIRTUAL_NAME}
    restart: always
    volumes:
      - phpmyadmin_session:/sessions
    env_file: .env

volumes:
  db_data:
  html:
  phpmyadmin_session:

networks:
  default:
    external:
      name: shared
